[[layers]]
    name = 'gtags'
    enable = 'executable("global")'

[[layers]]
    name = 'tags'
    enable = true

[[layers]]
    name = 'debug'
    enable = true

[[layers]]
    name = 'lang#c'
    enable = true

[[layers]]
    name = 'lang#javascript'
    enable = true

[[layers]]
    name = 'lang#python'
    enable = true

[[layers]]
    name = 'lang#sh'
    enable = true
    bash-file-head = [
        '#!/usr/bin/env bash',
        '# Time: `strftime("%Y-%m-%d %T")`',
        ''
    ]

[[layers]]
    name = 'lang#toml'
    enable = true

[[layers]]
    name = 'lang#vim'
    enable = true

[[layers]]
    name = 'lang#xml'
    enable = true

[[layers]]
    name = 'lang#markdown'
    enable = true
    enableWcwidth = 1
    listItemIndent = 1
    listItemChar = '-'

[[layers]]
    name = 'lsp'
    enable = true
    filetypes = [
        'c',
        'cpp',
        'python',
    ]
    #   [layers.override_cmd]
    #     c = ['ccls', '--log-file=/tmp/ccls.log']
    #     cpp = ['ccls', '--log-file=/tmp/ccls.log']

# The following plugins is for my personal file formats
[[custom_plugins]]
    name = 'thawk/vim-pcet'
    lazy = 1
    on_path = 'pcet_.*\.xml'

[[custom_plugins]]
    name = 'thawk/bbv2.vim'

