#!/bin/bash
# Command for running neovim

docker_image=thawk/spacevim-cpp

mkdir -p "${HOME}/.cache/SpaceVim"
mkdir -p "${HOME}/.local/share/nvim"

docker run --rm \
    -it \
    -P \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    -v "${HOME}":"${HOME}" \
    -v "${HOME}/.cache/SpaceVim":"/root/.cache/SpaceVim" \
    -v "${HOME}/.local/share/nvim":"/root/.local/share/nvim" \
    -w "${PWD}" \
    "${docker_image}" \
    -- "$@"

