#!/bin/bash
# Command for running neovim

docker_image=thawk/spacevim-cpp

docker run --rm \
    -it \
    -P \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    -v "${HOME}":"${HOME}" \
    -v "${HOME}/.cache/SpaceVim":"/root/.cache/SpaceVim" \
    "${docker_image}" \
    -- "$@"

